services:
  certbot:
    container_name: certbot
    hostname: certbot
    image: certbot/certbot:v2.11.0
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      local:
        ipv4_address: 11.5.0.3
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx:1.27.2-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/includes/:/etc/nginx/includes/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      tomcat:
      apache:
      local:
        ipv4_address: 11.5.0.2
networks:
  tomcat:
    name: tomcat_local
    external: true
  apache:
    name: apache_local
    external: true
  local:
    driver: bridge
    ipam:
      config:
        - subnet: 11.5.0.0/16
          gateway: 11.5.0.1
