version: "3.9"
services:
  certbot:
    container_name: certbot
    hostname: certbot
    image: certbot/certbot:v2.1.0
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      local:
        ipv4_address: 11.5.0.3
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx:1.23.2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf:/etc/nginx/conf.d:ro
      - ./html:/usr/share/nginx/html:ro
      - ./includes/:/etc/nginx/includes/:ro
      #- ./ssl/:/etc/ssl/certs/nginx/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    #command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      tomcat:
      apache:
      local:
        ipv4_address: 11.5.0.2
networks:
  tomcat:
    name: tomcat_local
    external: true
  apache:
    name: apache_local
    external: true
  local:
    driver: bridge
    ipam:
      config:
        - subnet: 11.5.0.0/16
          gateway: 11.5.0.1
